services:
  - type: web
    name: minecraft-java-command-school
    runtime: static
    buildCommand: "true"
    staticPublishPath: .
    autoDeployTrigger: commit
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
